# Numpy

> pip install numpy

In [4]:
import numpy as np

In [5]:
import sys
import time

# Compare native Python List with Numpy 


## 1. Memory Size

Normaly an integer variable takes 4x bytes -> 100x integers = 400x Bytes

Numpy consumes lower memory than python list


In [6]:
SIZE = 100

# Create Python List with 100x Integers
mylist = range(SIZE)
print(sys.getsizeof(5)  * SIZE  ) # 2800


# Create a Numpy Array
numpy_Array = np.array(SIZE)
print(numpy_Array.itemsize * SIZE) # 400x Bytes  ( 4x Bytes/Integer * 100)

2800
400


## Execution Time

Numpy is much faster than native python lists

In [7]:
SIZE = 1000000 # x Integers

# Create Python lists 
mylist1 = range(SIZE)
mylist2 = range(SIZE)

start_time = time.time() 
result = [ (x+y)  for x, y in zip(mylist1, mylist2)] # sum between mylist1 and mylist2
end_time = time.time()

print("Python Time:" , (end_time - start_time) * 1000) # 1000 for the precision

Python Time: 133.9569091796875


In [8]:
# Create Numpy Arrays

array1 = np.arange(SIZE)
array2 = np.arange(SIZE)

start_time = time.time()
result = array1 + array2 
end_time = time.time()

print("Numpy Time:" , (end_time - start_time) * 1000)

Numpy Time: 9.541749954223633


# Define Arrays

In [12]:
# 1. via a python native list
mylist = [1, 2 ,3,4,5]
print(mylist,type(mylist))


array = np.array(mylist)
print(array, type(array))

# 2. Define directly one dimernsional
array_1 = np.array([1,2,3,4,5])
print(array_1, type(array1))


# 2. Define multi dimernsional array
array_2 = np.array([ [1, 2 ] , [3, 4 ]   ])
print(array_2, type(array_2))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [15]:
# Define with specific data types
array_1 = np.array([1,2,3,4,5], dtype = np.float64) # 8x Bytes float
print(array_1)


array_1 = np.array([1,2,3,4,5], dtype = np.int32) # 4x Bytes int
print(array_1)

array_1 = np.array([1,2,3,4,5], dtype = np.complex) # complex zahlen
print(array_1)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


C:\Users\M\AppData\Local\Temp\ipykernel_11428\786061516.py:9: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  array_1 = np.array([1,2,3,4,5], dtype = np.complex) # complex zahlen


# Array Information

In [23]:
# Information for single dimensional array
array_1 = np.array([1,2,3,4,5])
print(array_1)



print(array_1.ndim) # 1  -> 1x vector with 5x items
print(array_1.shape) # (5,) --> 5x items in a vector
print(array_1.size) # 5x , count of items --> 
print(array_1.dtype) # Data Type> 
print(array_1.itemsize) # 4x Bytes for each item



[1 2 3 4 5]
1
(5,)
5
int32
4


In [30]:
# multi- dimensional array
array_2 = np.array([ [1, 2 ] , [3, 4 ] , [5, 6]  ])
print(array_2)


print(array_2.ndim) # 2x dimensions
print(array_2.shape) # (3, 2)  3x rows , 2x columns
print(array_2.size)  # 6 -> count of items
print(array_2.dtype)  # 6 -> Int32
print(array_2.itemsize)  # 4x Bytes for each item

[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
6
int32
4


# Mathematical Operations

In [32]:
a = np.arange(10)  # -> 0 - 9
b = np.arange(1, 11)  # -> 1 - 10

print(a + b)
print(a - b)
print(a * b)
print(a / b)

# Numpy Function
print(np.sqrt(a)) # Wurzel

[ 1  3  5  7  9 11 13 15 17 19]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
[ 0  2  6 12 20 30 42 56 72 90]
[0.         0.5        0.66666667 0.75       0.8        0.83333333
 0.85714286 0.875      0.88888889 0.9       ]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


# Functions

In [40]:
a = np.arange(10)  # -> 0 - 9
b = np.arange(1, 11)  # -> 1 - 10
c = np.array( [   [1,2], 
                  [3,4], 
                  [5,6]   
              ])


# Array functions
print(a.sum()) 
print(a.min()) 
print(a.max()) 
print(a.mean()) # average
print(c.sum()) # 1 + 2+ 3 + 4 + 5+ 6

# Advanced Sum
""" 
axis= 0 --> columns
axis= 1 --> rows
"""
print(c.sum(axis = 0)) # column-wise [ 9 12]
print(c.sum(axis = 1)) # row-wise [ 3  7 11]

print() 

# Sorting
a = np.array([ 5, 8, 2, 5,9,12,1,90,356,13 ])
a.sort()
print(a)


# Rounding 
a = np.array([5.0, 3.3, 2.123, 5.1547, 76.781, 8.8782 ])
print(a.round(decimals= 2))




45
0
9
4.5
21
[ 9 12]
[ 3  7 11]

[  1   2   5   5   8   9  12  13  90 356]
[ 5.    3.3   2.12  5.15 76.78  8.88]


# Accessing Items --> Slicing

In [47]:
c = np.array( [   [1,2], 
                  [3,4], 
                  [5,6]   
              ])


print(c.shape)

print(c[0]) # [1,2]
print(c[1]) # [3,4]
print(c[-1]) #  [5,6]  


print(c[::-1]) #  rückwerts


# Specific Item (R, C)
print(c[1, 1])

# Range of items (R, C)
print(c[ 0:2  ,  1:2  ])

(3, 2)
[1 2]
[3 4]
[5 6]
[[5 6]
 [3 4]
 [1 2]]
4
[[2]
 [4]]


# Generate Data

In [97]:
a = np.arange(30) # 0-29
b = np.arange(10,30) # 10-29

print(a)
print(b)


zeros = np.zeros( (3,4)  ) # only Zero , 3x rows , 4x columns
print(zeros)

ones = np.ones( (3,4)  ) #only 1 , 3x rows , 4x columns
print(ones)

numbers = np.full( (3,4),  5 ) # certain value, 3x rows , 4x columns
print(numbers)


# Equaly spaced 
numbers = np.linspace(1, 5 , 50) # 50x numbers between 1 and 5 , equal spaced
print(numbers)



# Identity Matrix
numbers = np.eye(5) # Identity Matrix
print(numbers)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Reshaping /Shaping

- Convert the shape of an array to another **compatible** shape

In [58]:
a = np.array( [   [1,2], 
                  [3,4], 
                  [5,6]   
              ])

print("Before Reshaping: ")
print(a, a.shape) # (3, 2)


# 1. Reshapre to 2x3
print("After Reshaping 1: ")
b = a.reshape(2, 3)
print(b, b.shape)


# 2. Reshapre to 6x1
print("After Reshaping 2: ")
c = a.reshape(6,1)
print(c, c.shape)


# 3. Reshape to a vector without column 
print("After Reshaping 3: ")
d = a.reshape(6,)
print(d, d.shape)



Before Reshaping: 
[[1 2]
 [3 4]
 [5 6]] (3, 2)
After Reshaping 1: 
[[1 2 3]
 [4 5 6]] (2, 3)
After Reshaping 2: 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)
After Reshaping 3: 
[1 2 3 4 5 6] (6,)


# Flattern

alternative to a.shape(6,)

In [60]:
a = np.array( [   [1,2], 
                  [3,4], 
                  [5,6]   
              ])

print(a, a.shape)


result = a.ravel()  # [1 2 3 4 5 6] (6,)
print(result, result.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


# Random

In [61]:
from numpy import random

In [80]:
# single random integer
x = random.randint(100)
print(x, type(x))



# 1x dim random array with integers
x = random.randint(100, size = (5,))
print(x, type(x))


# 1x dim random array with floats
x = random.uniform(100, size = (5,))
print(x, type(x))


# nx dim random array with integers
x = random.randint(100, size = (2 , 3))
print(x, type(x))

# nx dim random array with floats
x = random.uniform(100, size = (2 , 3))
print(x, type(x))

31 <class 'int'>
[97 82 36 23 16] <class 'numpy.ndarray'>
[80.27335239 91.6041515  55.30779257 83.36132213 13.29693704] <class 'numpy.ndarray'>
[[91 66 13]
 [39 90 35]] <class 'numpy.ndarray'>
[[51.89701906 64.58203573 77.56331422]
 [37.24588972  6.52146938 52.42002143]] <class 'numpy.ndarray'>


In [79]:
mylist = [1,2,3,4,5,6,7,8,9]

# Single choice 
x = random.choice(mylist)
print(x, type(x))

# 3x choices
x = random.choice(mylist, size= (3,))
print(x, type(x))


# 3x choices - multi dimensional
x = random.choice(mylist, size= (3,4))
print(x, type(x))

4 <class 'numpy.int32'>
[7 7 3] <class 'numpy.ndarray'>
[[2 3 9 9]
 [2 3 4 8]
 [1 7 7 7]] <class 'numpy.ndarray'>


# View

any change to the orignal, the view will be affected .And vice Versa

In [84]:
a = np.array([1,2,3,4,5])
b = a # b will refer to the same container as a

print(a)
print(b)


# Change the orignal
a[0] = 11
print(a)
print(b) # b will get the same changes

# Change the reference
b[1] = 22
print(a) # a will get the same changes as b
print(b)

[1 2 3 4 5]
[1 2 3 4 5]
[11  2  3  4  5]
[11  2  3  4  5]
[11 22  3  4  5]
[11 22  3  4  5]


# Copy

Unterschiedliche Containers

In [86]:
a = np.array([1,2,3,4,5])
b = a.copy() # create  different container with the same values

print(a)
print(b)



# Change the orignal
a[0] = 11
print(a)
print(b) # b stays same like before

# Change the reference
b[1] = 22
print(a) # a stays same like before
print(b)


[1 2 3 4 5]
[1 2 3 4 5]
[11  2  3  4  5]
[1 2 3 4 5]
[11  2  3  4  5]
[ 1 22  3  4  5]


# Vertical Stacking of Data

In [87]:
a = np.array( [   [1,2], 
                  [3,4], 
                  [5,6]   
              ])

b = np.array( [   [11,12], 
                  [13,14], 
                  [15,16]   
              ])


result = np.vstack( (a, b) )
print(result)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [11 12]
 [13 14]
 [15 16]]


# Horizontal Stacking of Data

add the first row of each container together in one row, then the next rows

In [88]:
a = np.array( [   [1,2], 
                  [3,4], 
                  [5,6]   
              ])

b = np.array( [   [11,12], 
                  [13,14], 
                  [15,16]   
              ])


result = np.hstack( (a, b) )
print(result)

[[ 1  2 11 12]
 [ 3  4 13 14]
 [ 5  6 15 16]]


# Where()

In [89]:
a = np.array([1,2,3,4,5])
b = np.array([1,3,2,4,5])

# The positions where a == b
print(np.where(a == b)) # [0, 3, 4]

(array([0, 3, 4], dtype=int64),)


# Transpose()

- 1st column --> 1st row
- 2nd column --> 2nd row
- ...

In [92]:
a = np.array( [   [1,2], 
                  [3,4], 
                  [5,6]   
              ])
print(a)

print()


result = a.T # Transpose
print(result)

[[1 2]
 [3 4]
 [5 6]]

[[1 3 5]
 [2 4 6]]


# Dates

In [95]:
yesterday = np.datetime64("today", "D") - np.timedelta64(1, "D")
today = np.datetime64("today", "D")
tomorrow = np.datetime64("today", "D") + np.timedelta64(1, "D")


print(yesterday)
print(today)
print(tomorrow)

2023-02-26
2023-02-27
2023-02-28


In [96]:
# Generate Dates between two dates
result = np.arange("2023-02-27", "2023-03-15", dtype="datetime64[D]")
print(result)

['2023-02-27' '2023-02-28' '2023-03-01' '2023-03-02' '2023-03-03'
 '2023-03-04' '2023-03-05' '2023-03-06' '2023-03-07' '2023-03-08'
 '2023-03-09' '2023-03-10' '2023-03-11' '2023-03-12' '2023-03-13'
 '2023-03-14']
